### ISSUE TITLE
생성된 시계열 데이터를 giganto로 전송

### ISSUE THREAD

**Issue by sehkone** [aicers/crusher#12]
Crusher가 생성한 시계열 데이터를 giganto로 전송합니다. 데이터는 다음을 포함합니다.

- 모델 ID
- 주기(period) 시작 시각:  `DateTime<Utc>`
- 시계열 데이터: `Vec<f64>`

**Comment by BLYKIM** [comment]
@sehkone 
현재 Giganto에서 구현된 시계열 데이터 수신 형태는 [Giganto의 이슈 #125](https://github.com/aicers/giganto/issues/125)에 따라
 
 - kind: `String`
 - start: `i64`
 - period: `i64`
 - data: `Vec<f64>`

의 형태로 수신하고 있으며, 현재 Giganto에서 DB에 저장하는 형태는

key가 `source, kind, start` 이고 value로 `period, data` 를 저장하고 있습니다.

이것을 수신

- model_id: `String`
- start: `i64`
- data: `Vec<f64>`

저장

key: `source, model_id, start` , value: `model_id, data`
로 변경하면 될까요?

확인 부탁드립니다.

**Comment by sehkone** [comment]
`source`는 센서 노드, 그러니까 piglet을 말하는 것이죠? 이 정보는 모델에 포함되므로, giganto에서는 `model_id`와 `start`만 key로 사용하면 됩니다.

**Comment by BLYKIM** [comment]
여기서의 `source`는 시계열데이터를 보내주는 연결된 crusher의 source입니다

**Comment by sehkone** [comment]
같은 데이터, 같은 모델에 대해서 복수 crusher가 각자 생성한 시계열을 보내는 상황은 안 만들어야 하므로 `source`를 넣을 필요는 없을 것 같아요. 그리고, value에 `model_id`도 넣는 이유는 뭔가요?

**Comment by BLYKIM** [comment]
네 알겠습니다.
DB에 저장된 시계열 data를 보내줄 때 model_id에 대한 data만 필요로 한다면
value에서는 빼도 될 것 같습니다.

**Comment by kimhanbeom** [comment]
@BLYKIM @sehkone 

해당 내용 정리하여 다시 올립니다.

1. crusher에서 giganto의 time series 채널 연결
 - time_series 타입 전송 : 0x05 (u32,litten endian)
 
2. crusher에서 생성된 시계열 데이터 전송
 - start : i64 (little endian)          //주기 시작
 - data size:  u32 (little endian) //시계열 데이터 사이즈 
 - data : bincode serialize          //시계열 데이터 (data는 구조체로 필드는 다음과 같이 정의)
   1) model_id : String 
   2) data : Vec<f64>

3.giganto에서 데이터를 저장
 key : model_id + start
 value: data
